data:
  # dataset config
  type: anyloc.datasets.base_datasets
  split: val
  dataset_name: pitts250k
  dataset_folder: data/
  output_path: retrieval_results/
  image_ext: jpg
  max_img_size: 1024 # Maximum edge length (expected) across all images (GPU OOM)
  positive_dist_threshold: 25
  # dataloader config only used when cached is False
  num_workers: 4
  batch_size: 8
  shuffle: False

topk:
- 1
- 5
- 10
- 20
- 50
- 100
- 200

model:
# default model of AnyLoc
  type: anyloc.models.anyloc_dinov2
  domain: urban # 'aerial', 'indoor', 'urban'
  num_c: 32 # num of cluster in VLAD
  desc_layer: 31 # layer of descriptor
  desc_facet: value # 'query', 'key', 'value', 'token'

pairs_from_retrieval:
  num_processes: 20
  retrieval_results: data/pitts250k/retrieval_results/val/indices_200.npy
  output_path: data/pitts250k/retrieval_results/val/pairs_200.npy