data:
  # cached or not
  cached: True
  # dataset config
  type: anyloc.datasets.base_datasets
  split: train
  dataset_name: pitts250k
  dataset_folder: data/
  image_ext: jpg
  max_img_size: 1024 # Maximum edge length (expected) across all images (GPU OOM)
  positive_dist_threshold: 25
  # dataloader config only used when cached is False
  num_workers: 4
  batch_size: 8
  shuffle: False

topk: 20
