data:
  type: doppelgangers.datasets.pairwise_disambiguation_dataset
  num_workers: 4  
  train:
    image_dir: ['data/pitts30k/images/train']
    loftr_match_dir: ['data/pitts30k/retrieval_results/train/loftr_matches']
    batch_size: 16
    img_size: 640
    pair_path: ['data/pitts30k/retrieval_results/train/pairs_info_20.npy']
  test:
    image_dir: ['data/pitts30k/images/test']
    loftr_match_dir: ['data/pitts30k/retrieval_results/test/loftr_matches']
    batch_size: 16
    img_size: 640
    pair_path: ['data/pitts30k/retrieval_results/test/pairs_info_20.npy']

models:
  decoder:
    type: doppelgangers.models.cnn_classifier
    input_dim: 10

trainer:
  type: trainers.doppelgangers_trainer
  epochs: 20
  seed: 100
  opt:
    type: 'adam'
    lr: 5e-4  #  use default learning rate
    beta1: 0.9
    beta2: 0.999
    momentum: 0.9  # for SGD
    weight_decay: 0.
    scheduler: 'linear'
    step_epoch: 10

viz:
  log_freq: 10
  save_freq: 1
  val_freq: 10000